# Generated by Django 4.0.4 on 2022-05-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alternate_titles', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('GE', 'Germany'), ('IT', 'Italy'), ('SP', 'Spain'), ('US', 'United States')], max_length=2)),
                ('year', models.SmallIntegerField()),
                ('youtube_link', models.URLField()),
                ('actors', models.ManyToManyField(to='giallo.actors')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giallo.directors')),
            ],
        ),
    ]
