# Generated by Django 4.0.4 on 2022-05-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giallo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='Directors',
            new_name='Director',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
