# Generated by Django 4.0.4 on 2022-05-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giallo', '0002_rename_actors_actor_rename_directors_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='alternate_titles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
