# Generated by Django 4.0.4 on 2022-05-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giallo', '0003_alter_movie_alternate_titles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='giallo.actor'),
        ),
    ]
