# Generated by Django 4.0.4 on 2022-05-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giallo', '0005_alter_actor_options_alter_director_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rotten_tomatoes_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='wikipedia_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
