# Generated by Django 4.0.4 on 2022-05-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giallo', '0006_movie_imdb_link_movie_rotten_tomatoes_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='amazon_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tubi_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
